server:
    port: 8888
spring:
    profiles:
        active: native
    application:
      name: CONFIG-SERVER
    cloud:
        config:
            server:
                native:
                    searchLocations: file:///D:/learn/configfiles/
